name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install libncurses-dev
      run: sudo apt-get install libncurses-dev
    - name: install autotools-dev
      run: sudo apt-get install autotools-dev
    - name: install aclocal
      run: sudo apt-get install aclocal
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
