name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: ncurses
      run: npm install ncurses
    - name: glibc6
      run: npm install glibc6
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: install
      run: make install
